export enum LocalStorageVariables {
    ACCESS_TOKEN = 'access_token',
    ACCESS_TOKEN_PG = 'access_token_pg',
    ACCESS_TOKEN_AUTHE_MV = 'access_token_authe_mv',
    REFRESH_TOKEN_AUTHE_MV = 'refresh_token_authetication_mv',
    ID = 'id',
    USUARIO = 'usuario',
    EXPIRES_AT  = 'expires_at',
    LONGITUDE = 'longitude',
    LATITUDE = 'latitude',
    NEW_TERM_USE = 'new_term_use',
    BOAS_VINDAS_MOB = 'boas_vindas_mob',
    CONTRATO = 'contrato',
    USER_ID_ADMIN = 'user_id_admin',
    NEW_RECIBO = 'new_recibo',
    PRODUCTION_MODE = 'production_mode',
    URL_DEFAULT_PDF = 'url_default_pdf',
}